using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reg2InfUI.INF_writing
{
	static class INF_start
	{
		public static void generate_text()
		{
			Variables.INF_content += "; Auto generated by Reg2InfUI \n \n";
		}
	}
}
